import type { ChainConfig, ChainId } from './types.js';

const chains: Record<ChainId, ChainConfig> = {
  ethereum: {
    id: 'ethereum',
    name: 'Ethereum',
    type: 'evm',
    chainId: 1,
    explorer: 'https://etherscan.io',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'ETH',
  },
  base: {
    id: 'base',
    name: 'Base',
    type: 'evm',
    chainId: 8453,
    explorer: 'https://basescan.org',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'ETH',
  },
  arbitrum: {
    id: 'arbitrum',
    name: 'Arbitrum',
    type: 'evm',
    chainId: 42161,
    explorer: 'https://arbiscan.io',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'ETH',
  },
  bnb: {
    id: 'bnb',
    name: 'BNB Chain',
    type: 'evm',
    chainId: 56,
    explorer: 'https://bscscan.com',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'BNB',
  },
  polygon: {
    id: 'polygon',
    name: 'Polygon',
    type: 'evm',
    chainId: 137,
    explorer: 'https://polygonscan.com',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'POL',
  },
  optimism: {
    id: 'optimism',
    name: 'Optimism',
    type: 'evm',
    chainId: 10,
    explorer: 'https://optimistic.etherscan.io',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'ETH',
  },
  avalanche: {
    id: 'avalanche',
    name: 'Avalanche',
    type: 'evm',
    chainId: 43114,
    explorer: 'https://snowtrace.io',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'AVAX',
  },
  gnosis: {
    id: 'gnosis',
    name: 'Gnosis',
    type: 'evm',
    chainId: 100,
    explorer: 'https://gnosisscan.io',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'xDAI',
  },
  berachain: {
    id: 'berachain',
    name: 'Berachain',
    type: 'evm',
    chainId: 80094,
    explorer: 'https://berascan.com',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'BERA',
  },
  monad: {
    id: 'monad',
    name: 'Monad',
    type: 'evm',
    chainId: 143,
    explorer: 'https://explorer.monad.xyz',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'MON',
  },
  aurora: {
    id: 'aurora',
    name: 'Aurora',
    type: 'evm',
    chainId: 1313161554,
    explorer: 'https://explorer.aurora.dev',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'ETH',
  },
  xlayer: {
    id: 'xlayer',
    name: 'X Layer',
    type: 'evm',
    chainId: 196,
    explorer: 'https://www.oklink.com/xlayer',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'OKB',
  },
  near: {
    id: 'near',
    name: 'NEAR',
    type: 'account',
    explorer: 'https://nearblocks.io',
    explorerTxPath: '/txns/{hash}',
    nativeToken: 'NEAR',
  },
  solana: {
    id: 'solana',
    name: 'Solana',
    type: 'account',
    explorer: 'https://solscan.io',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'SOL',
  },
  sui: {
    id: 'sui',
    name: 'Sui',
    type: 'move',
    explorer: 'https://suiscan.xyz',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'SUI',
  },
  bitcoin: {
    id: 'bitcoin',
    name: 'Bitcoin',
    type: 'utxo',
    explorer: 'https://mempool.space',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'BTC',
  },
  litecoin: {
    id: 'litecoin',
    name: 'Litecoin',
    type: 'utxo',
    explorer: 'https://litecoinspace.org',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'LTC',
  },
  dogecoin: {
    id: 'dogecoin',
    name: 'Dogecoin',
    type: 'utxo',
    explorer: 'https://dogechain.info',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'DOGE',
  },
  bitcoincash: {
    id: 'bitcoincash',
    name: 'Bitcoin Cash',
    type: 'utxo',
    explorer: 'https://blockchair.com/bitcoin-cash',
    explorerTxPath: '/transaction/{hash}',
    nativeToken: 'BCH',
  },
  tron: {
    id: 'tron',
    name: 'Tron',
    type: 'account',
    explorer: 'https://tronscan.org',
    explorerTxPath: '/#/transaction/{hash}',
    nativeToken: 'TRX',
  },
  ton: {
    id: 'ton',
    name: 'TON',
    type: 'account',
    explorer: 'https://tonscan.org',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'TON',
  },
  stellar: {
    id: 'stellar',
    name: 'Stellar',
    type: 'account',
    explorer: 'https://stellarchain.io',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'XLM',
  },
  xrp: {
    id: 'xrp',
    name: 'XRP Ledger',
    type: 'account',
    explorer: 'https://xrpscan.com',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'XRP',
  },
  starknet: {
    id: 'starknet',
    name: 'Starknet',
    type: 'account',
    explorer: 'https://starkscan.co',
    explorerTxPath: '/tx/{hash}',
    nativeToken: 'STRK',
  },
  cardano: {
    id: 'cardano',
    name: 'Cardano',
    type: 'account',
    explorer: 'https://cardanoscan.io',
    explorerTxPath: '/transaction/{hash}',
    nativeToken: 'ADA',
  },
  aptos: {
    id: 'aptos',
    name: 'Aptos',
    type: 'move',
    explorer: 'https://aptoscan.com',
    explorerTxPath: '/transaction/{hash}',
    nativeToken: 'APT',
  },
  aleo: {
    id: 'aleo',
    name: 'Aleo',
    type: 'account',
    explorer: 'https://aleoscan.io',
    explorerTxPath: '/transaction/{hash}',
    nativeToken: 'ALEO',
  },
  zcash: {
    id: 'zcash',
    name: 'Zcash',
    type: 'utxo',
    explorer: 'https://blockchair.com/zcash',
    explorerTxPath: '/transaction/{hash}',
    nativeToken: 'ZEC',
  },
};

/** Get configuration for a specific chain */
export function getChainConfig(chainId: ChainId): ChainConfig {
  return chains[chainId];
}

/** Get all supported chain configurations */
export function getAllChains(): ChainConfig[] {
  return Object.values(chains);
}

/** Get the explorer URL for a transaction */
export function getExplorerTxUrl(chainId: ChainId, txHash: string): string {
  const chain = chains[chainId];
  return chain.explorer + chain.explorerTxPath.replace('{hash}', txHash);
}
